### ISSUE TITLE
Missing default login scopes to allow requesting incremental scopes

### ISSUE THREAD

**Issue by DavideSilva** [synth/omniauth-microsoft_graph#13]
When attempting to use this strategy with the OmniAuth setup phase, we are unable to login. 

The [OmniAuth setup phase](https://github.com/omniauth/omniauth/wiki/Setup-Phase) allows us to incrementally request scopes by using a `#setup` method in the Sessions controller, for example. 

This strategy is failing due to missing the `DEFAULT_SCOPES` that other OmniAuth strategies have. An example is the [Google OAuth2 strategy](https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb). They allow passing scopes in the `params` but fallback to scopes that simply allow login if none were passed.

The fix for this should be something like this but I haven't tested it

```
DEFAULT_SCOPES = 'openid email profile User.Read'
```

```
      def authorize_params
        super.tap do |params|
          %w[display score auth_type].each do |v|
            if request.params[v]
              params[v.to_sym] = request.params[v]
            end
          params[:scope] ||= DEFAULT_SCOPES
          end
        end
      end
```

**Comment by synth** [comment]
Thanks for the report. Pull requests are welcome! :)

**Comment by synth** [comment]
@DavideSilva I upgraded things and included a DEFAULT_SCOPE. Can you check if the 0.3.1 release meets your needs or has any bugs?

**Comment by synth** [comment]
I assume things have worked out or you have moved on ✌️
