### ISSUE TITLE
omniauth-microsoft_graph + Devise.

### ISSUE THREAD

**Issue by Nico27** [synth/omniauth-microsoft_graph#16]
Hi!
Is there any tutorial to implemente omniauth-microsoft_graph with Devise on Rails 6?
Thanks!

**Comment by synth** [comment]
Hi @Nico27. Sorry, I don't have a specific tutorial on this. But this is standard omniauth provider, so any other tutorial should work. I google'd and found this: https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview

Good luck.
