### ISSUE TITLE
Email not found

### ISSUE THREAD

**Issue by andresgutgon** [synth/omniauth-microsoft_graph#17]
# What?
Hi, I'm trying to do Single Sign on but `email` is not returned if I try `request.env['omniauth.auth'].info.email`. This is returning `nil` in my personal hotmail account. 
I managed to get the email here: 
```
request.env['omniauth.auth'].extra.raw_info['userPrincipalName']
```

Do you know why this can be? Could make sense to also find the email there as a fallback?

This are the permissions I have in my Azure application
![image](https://user-images.githubusercontent.com/49499/85229336-66b34d00-b3e9-11ea-8535-2ddc822e20e1.png)

**Comment by synth** [comment]
This is not meant to be used with personal hotmail, or perhaps even personal (Live) Microsoft accounts. Can you please try with  a proper Office365 account. Closing for now as I presume this is issue with Hotmail, not with the gem. We can re-open if you find a further issue with a proper email account.

**Comment by andresgutgon** [comment]
Thanks for the answer. Makes sense although a cover this case would be helpful and not much work imo

**Comment by synth** [comment]
@andresgutgon Sure. It may be a matter of adapting to the correct field. But not sure, I don't have a hotmail acct to test.  Happy to take PRs if you can get it to work :)

**Comment by synth** [comment]
Btw, one way to test outside of this gem, is to check authentication using the Graph API explorer: https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by krisleech** [comment]
Same occurs for a `username@companyname.onmicrosoft.com` email address.

**Comment by stevenou** [comment]
> > fwiw I have the same issue with Outlook account and had to fallback to `extra.raw_info['userPrincipalName']` in my application code.
> 
> how did you fallback? in the `OmniauthCallbacksController` ? I am using my fork for now: #33

maybe you're using this with another library like `devise`? in that case your fork probably makes sense. 

if using `omniauth-microsoft_graph` directly, instead of calling `request.env['omniauth.auth']['info'][email']` where you need the email, just call `request.env['omniauth.auth'].extra.raw_info['userPrincipalName']`.

**Comment by bettysteger** [comment]
> > > fwiw I have the same issue with Outlook account and had to fallback to `extra.raw_info['userPrincipalName']` in my application code.
> > 
> > 
> > how did you fallback? in the `OmniauthCallbacksController` ? I am using my fork for now: #33
> 
> maybe you're using this with another library like `devise`? in that case your fork probably makes sense.
> 
> if using `omniauth-microsoft_graph` directly, instead of calling `request.env['omniauth.auth']['info'][email']` where you need the email, just call `request.env['omniauth.auth'].extra.raw_info['userPrincipalName']`.

yes i am using devise and devise-token-auth ;)
