### ISSUE TITLE
Refresh token missing from callback data...?

### ISSUE THREAD

**Issue by greg-asc** [synth/omniauth-microsoft_graph#18]
Hi,

I'm using `omniauth-microsoft_graph` for connecting with Microsoft Graph to import user's contacts. I have no problem signing users in and using the returned token to import data from MS Graph API. However, the callback doesn't return a refresh token for some reason. Here's what it looks like:
```
{
  "provider":  "...",
  "uid":       "...",
  "info": {
    "email":       "...",
    "first_name":  "...",
    "last_name":   "...",
    "name":        "...",
    "nickname":    "..."
  },
  "credentials": {
    "token":       "...",
    "expires_at":  1597674066,
    "expires":     true
  },
  "extra": {
    "raw_info": {
      "@odata.context":     "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
      "businessPhones":     [],
      "displayName":        "...",
      "givenName":          "...",
      "jobTitle":           null,
      "mail":               "...",
      "mobilePhone":        null,
      "officeLocation":     null,
      "preferredLanguage":  "en-GB",
      "surname":            "...",
      "userPrincipalName":  "...",
      "id":                 "..."
    },
    "params": {
      "token_type":      "Bearer",
      "scope":           "Contacts.Read User.Read profile openid email",
      "ext_expires_in":  3599
    }
  }
}
```

Because of other gems I can only use version `0.2.1` and I'm wondering if that could be the problem? Or is that unrelated?

Thanks!

**Comment by synth** [comment]
@greg-asc I'm not sure. Your best bet is to try a fresh application with the latest version and see if the refresh token comes through that. Another thought is the scopes defined in your application on Microsoft's side. 

Also, what gem conflict is preventing your from upgrading? Omniauth? I highly recommend you upgrade to Omniauth's versions that are supported by this gem as there are major security fixes in there you will want if you're working on a production application.

**Comment by greg-asc** [comment]
Hi @synth! For some reason I forgot to add `openid` and `offline_access` to my app scopes. I'm not sure which one was responsible for the missing refresh token but that did the job. Now the response includes the refresh token as well.

And to answer your question, I am indeed planning to use it in production and the reason why I'm currently stuck on version `0.2.1` is because `omniauth-slack` requires an older version of `omniauth-oauth2`, which is in conflict with `0.3.3`.

Anyway, thanks for helping me out!

**Comment by synth** [comment]
Ah yes, I believe its `offline_access` that gives you the refresh token. No problem, take care :)
