### ISSUE TITLE
Authentication failure invalid_credentials: CSRF detected

### ISSUE THREAD

**Issue by GMolini** [synth/omniauth-microsoft_graph#19]
Hi,

Im trying to develop an addin for outlook. The addin backend is developed in rails, and I am using the [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) gem for authentication.
Im using this gem to be able to use oauth and get the user to log in to the application. In my addin, I use a frame to get the /auth/microsoft_graph url and thus start the authentication process.

When I use the addin from the outlook standalone app, authentication runs smoothly and Im able to successfully log in. But if I try to open the addin on [outlook for the web](https://outlook.office.com/mail/inbox) i get an CSRF error

```
Started GET "/auth/microsoft_graph" for 185.227.213.4 at 2021-01-21 12:37:21 +0100
   (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Started GET "/omniauth/microsoft_graph?resource_class=User" for 185.227.213.4 at 2021-01-21 12:37:21 +0100
I, [2021-01-21T12:37:21.665192 #54893]  INFO -- omniauth: (microsoft_graph) Request phase initiated.
   (0.1ms)  BEGIN
  ActiveRecord::SessionStore::Session Update (0.4ms)  UPDATE "sessions" SET "data" = $1, "updated_at" = $2 WHERE "sessions"."id" = $3  [["data", "BLABLA\n"], ["updated_at", "2021-01-21 11:37:21.695389"], ["id", 4182]]
   (0.7ms)  COMMIT
Started GET "/omniauth/microsoft_graph/callback?code=blabla&state=blabla&session_state=blablabla" for 185.227.213.4 at 2021-01-21 12:37:22 +0100
I, [2021-01-21T12:37:22.041232 #54893]  INFO -- omniauth: (microsoft_graph) Callback phase initiated.
E, [2021-01-21T12:37:22.046415 #54893] ERROR -- omniauth: (microsoft_graph) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
E, [2021-01-21T12:37:22.046462 #54893] ERROR -- omniauth: (microsoft_graph) Authentication failure! invalid_credentials: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
  
```

I have tried setting ```provider_ignores_state: true``` int the omniauth.rb config
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :microsoft_graph, ENV['AZURE_APPLICATION_CLIENT_ID'], ENV['AZURE_APPLICATION_CLIENT_SECRET'],
    provider_ignores_state: true,
    scope: ENV['AZURE_SCOPE']
end 
```

but that then gives a ```NotImplementedError (no default_devise_mapping set):``` error.

Do you have any suggesstion?

**Comment by synth** [comment]
So, I'm not too sure about devise. But my guess is because you are doing a GET request against the auth link. Try a POST request which includes the csrf headers. Omniauth no longer permits GET requests against auth links (hence the CSRF issue) due to security vulnerability.

**Comment by lauer** [comment]
It works for me using devise, when I define the `provider_ignore_states: true`

```
  config.omniauth :microsoft_graph,
                  ENV.fetch('AZURE_APP_ID', nil),
                  ENV.fetch('AZURE_APP_SECRET', nil),
                  scope: ENV.fetch('AZURE_SCOPES', nil),
                  provider_ignores_state: true
```

I also have this gem added to my Gemfile. 
```
gem 'omniauth-rails_csrf_protection', '~> 0.1.2'
```

**Comment by GMolini** [comment]
@synth : That may well be the issue, but how can I include the CSRF headers if my front is not the rails app? The rails app is just an API backend.

@lauer: Im not exactly using devise, but [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) If I use the ```provider_ignores_state: true``` option then it gives an error ```NotImplementedError (no default_devise_mapping set)```

**Comment by synth** [comment]
@GMolini I can't really advise on that. Do you have separate API authentication? If so, likely you just want to turn off csrf protection: https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html - but do so at your own risk.

Alternatively, you would build a mechanism for including the csrf token in the front end head metatag, just as Rails does.

**Comment by GMolini** [comment]
Mmm, so, Ive been digging a little, and I think the problem is that when I use the ```provider_ignores_state: true```, rails is not saving the session (only when it comes from the frame). I dont really know why that happens, but it does seem likely that its not this gems fault. (but anyway, if you have any ideas, they are more than welcome!)

**Comment by synth** [comment]
Does your browser console give any hints? If you're in an iframe, you may be hitting a same-site cookie issue. Trying turning off same site protection from Rails.

**Comment by GMolini** [comment]
Thanks for the help, but I have tried that and it doesnt work. Anyway, Im closing this issue as it has nothing to do with this gem. Thanks again!
