### ISSUE TITLE
Unable to login / microsoft says "reply address" is different but it isn't

### ISSUE THREAD

**Issue by martini** [synth/omniauth-microsoft_graph#2]
I registered an app at microsoft. If I use omniauth-microsoft_graph I always get the following error. I notice, I already added `https://me.zammad.com/auth/microsoft_graph/callback` as Redirect URLs  in https://apps.dev.microsoft.com/#/appList - it seems that microsoft is not accepting the http params `?code=ABC&state=123&session_state=456`. Any hint would be wonderful!

```
invalid_client: AADSTS70002: Error validating credentials.
AADSTS50011: The reply address 'https://me.zammad.com/auth/microsoft_graph/callback?code=ABC&state=123&session_state=456' does not match the reply address 'https://me.zammad.com/auth/microsoft_graph/callback' provided when requesting Authorization code.
Trace ID: a7deb585-be07-40fc-8a63-d78dfd07xxxx
Correlation ID: a1c9b81e-5ac6-4b1a-befb-97b12e37xxxx
Timestamp: 2017-07-13 14:18:36Z
{
  "error":"invalid_client",
  "error_description":"AADSTS70002: Error validating credentials. AADSTS50011: The reply address 'https://me.zammad.com/auth/microsoft_graph/callback?code=ABC&session_state=456' does not match the reply address 'https://me.zammad.com/auth/microsoft_graph/callback' provided when requesting Authorization code.\r\nTrace ID: a7deb585-be07-40fc-8a63-d78dfd07xxxx\r\nCorrelation ID: a1c9b81e-5ac6-4b1a-befb-97b12e37xxxx\r\nTimestamp: 2017-07-13 14:18:36Z",
  "error_codes":[70002,50011],
  "timestamp":"2017-07-13 14:18:36Z",
  "trace_id":"a7deb585-be07-40fc-8a63-d78dfd07xxxx",
  "correlation_id":"a1c9b81e-5ac6-4b1a-befb-97b12e37xxxx"
}
```

Used gems:

```
$ bundle show |grep omni
  * omniauth (1.6.1)
  * omniauth-facebook (4.0.0)
  * omniauth-github (1.3.0)
  * omniauth-gitlab (1.0.2)
  * omniauth-google-oauth2 (0.5.0)
  * omniauth-linkedin-oauth2 (0.1.5)
  * omniauth-microsoft_graph (0.1.0)
  * omniauth-oauth (1.1.0)
  * omniauth-oauth2 (1.4.0)
  * omniauth-twitter (1.2.1)
```

Ruby:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
````

**Comment by synth** [comment]
Does it work if you exclude the GET parameters? With OAuth (and OmniAuth), if you want to pass parameters through the process, you need to do it in a special way. Perhaps see this article: https://stackoverflow.com/questions/9890985/passing-parameters-through-omniauth

**Comment by synth** [comment]
@martini we actually ran into a similar issue. Our error was:

    AADSTS90102: 'redirect_uri' value must be a valid absolute Uri.

The problem is a bug (?) in omniauth when it tries to parse the url and there is a character in it that doesn't pass its regex. Our url was from Microsoft that looked like: 

    /auth/microsoft_graph?redirect=%2F%3Fclose_on_open%3Dtrue%26referrer%3Doutlook.office365.com%26viewer%3Doutlook&referrer=outlook.office365.com&viewer=outlook&_host_Info=outlook|web|16.01|en-us|693b605c-d515-98a8-6e63-7049e094acf3|isDialog

It was the pipe '|' character that caused an issue with omniauth causing the #full_host method to return nil which MS doesn't like.

The fix is to define the full_host as follows:

    #config/initializers/omniauth.rb
    #Rails.application.config.host is something we define on our app based upon environment
    OmniAuth.config.full_host = Rails.application.config.host

You can also specify as a proc:

    #config/initializers/omniauth.rb
    OmniAuth.config.full_host = Proc.new{|env| Rails.application.config.host}
