### ISSUE TITLE
Getting OAuth2 Authorization code was already redeemed error

### ISSUE THREAD

**Issue by lauer** [synth/omniauth-microsoft_graph#21]
I am getting this error, after upgradering the gem to 0.3.3 and added as a devise omniauth. 

```
I, [2021-03-02T21:35:28.041607 #13350]  INFO -- omniauth: (microsoft_graph) Callback phase initiated.
I, [2021-03-02T21:35:28.812240 #13350]  INFO -- omniauth: (microsoft_graph) Callback phase initiated.
E, [2021-03-02T21:35:29.296444 #13350] ERROR -- omniauth: (microsoft_graph) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.
```

My devise config looks like this
```
  config.omniauth :microsoft_graph,
                  ENV.fetch('AZURE_APP_ID', nil),
                  ENV.fetch('AZURE_APP_SECRET', nil),
                  scope: ENV.fetch('AZURE_SCOPES', nil),
                  provider_ignores_state: true
```

Where scopes are the following: 
`AZURE_SCOPES = "openid profile email offline_access user.read tasks.read calendars.readwrite"`

So it should have the refresh token. 

```
devise (4.7.1)    
oauth2 (1.4.4)
omniauth (1.9.1)
omniauth-microsoft_graph (0.3.3)
omniauth-oauth2 (1.7.1)
omniauth-rails_csrf_protection (0.1.2)
rails 6.1.3
ruby 2.6.3
```

Why isn't he gem handle/use the refresh token? And how can I debug this more?

**Comment by synth** [comment]
We use refresh token in our app and don't have issue. This our config: 
```
    provider :microsoft_graph, 
      ENV['o365']['client_id'],
      ENV['o365']['secret'],
      {
       setup: true,
      }

```

You may need the `setup` option. NOTE: You need to do more than just specify the setup option. You also need a setup action on the controller as well. Thats a bit beyond the support I can provide, but try to look up more about how the `setup` configuration works on Omniauth.

**Comment by lauer** [comment]
But you are not using it together with Devise?

It actually seems like it works, because I get the token back in the callback, with an ext_expires_in=3599.
Maybe it does not store the session correct in my session table.

**Comment by synth** [comment]
We use authlogic. I always had problems with Devise, not sure why. 

So, if you're getting the refresh token on authentication, then yes, its working. We have special code that automatically refreshes the token whenever we catch a token expired exception. 

If you're getting the refresh token, are you also "refreshing" it? Here is our code: 
```ruby
        response    = RestClient.post "https://login.microsoftonline.com/common/oauth2/v2.0/token", 
          :grant_type => 'refresh_token', 
          :refresh_token => refresh_token, 
          :client_id =>ENV['o365']['client_id'], 
          :client_secret => ENV['o365']['secret'] 
```

**Comment by lauer** [comment]
Sorry. Closing this. 

I had defined this OmniAuth in both its own initializers file and in devise.
