### ISSUE TITLE
Support omniauth 2.0

### ISSUE THREAD

**Issue by lauer** [synth/omniauth-microsoft_graph#22]
Is there anything stopping this from being supported by OmniAuth 2.0 and Omniauth-Oauth2 1.0?

**Comment by synth** [comment]
Just needs a PR and confirmation that its working. Feel free to submit!

**Comment by mjarmula** [comment]
Hey, seems like no one has picked that up. @synth, can I try to submit PR?

**Comment by synth** [comment]
Sure thing :)
