### ISSUE TITLE
Common endpoint is not supported for single-tenant app registrations

### ISSUE THREAD

**Issue by SirRawlins** [synth/omniauth-microsoft_graph#23]
Good morning 👋 

I started trying to use this gem this morning to authenticate users within my organisation, during the app registration with Microsoft we select the "Accounts in this organizational directory only (Single tenant)" option.

However, it seems that the endpoints for single-tenant app registrations include the Tenant ID, and don't use the `/common` URL.

Trying to use this gem provider with a single-tenant app registration results in the following error once directed to Microsoft.

> Application 'xxx' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

I'm thinking that the Tenant ID should be an optional config variable alongside the Client ID and Client Secret, and if one is provided it should be used in the generation of the `authorize_url` and `token_url`, only falling back to `/common` if one is not provided?

Appreciate any thoughts on this.

**Comment by hugodemiglio** [comment]
Config variable to Tenant ID should be great!

For now, you can simple modify some parameters to set on URL generation:
```ruby
config.omniauth :microsoft_graph, ENV['AD_CLIENT_ID'], ENV['AD_CLIENT_SECRET'], client_options: {
  site:          'https://login.microsoftonline.com/',
  token_url:     "#{ENV['AD_TENANT']}/oauth2/v2.0/token",
  authorize_url: "#{ENV['AD_TENANT']}/oauth2/v2.0/authorize"
}
```

Thank you!

**Comment by SirRawlins** [comment]
Thanks for the great suggestion @hugodemiglio 

I also found that I can change the URLs in the client_options hash during the Omniauth "setup" phase too. https://github.com/omniauth/omniauth/wiki/Setup-Phase

**Comment by synth** [comment]
Great, sounds like we can close this then. Cheers.
