### ISSUE TITLE
Authentication failure (JWT::DecodeError)

### ISSUE THREAD

**Issue by pixiitech** [synth/omniauth-microsoft_graph#36]
Some accounts are failing with this error while other work without any issues:
![dummy](https://github.com/synth/omniauth-microsoft_graph/assets/18196351/fb9a0321-6529-478a-a000-1b8758ddb697)

ERROR -- omniauth: (microsoft_graph) Authentication Failure! Could not find public key for kid ----------

This 'kid' key doesn't match what I have set for my environment variables

**Comment by synth** [comment]
Can you check if the authenticating user has `mail` attribute set in Entra? I have seen authentication fail when this attribute is missing.

**Comment by iandonovan** [comment]
@synth (I'm working on this with @pixiitech )

The admin/azure account has an email attribute set. The (Outlook) account attempting to log in via omniauth also has an email set up. This issue does not occur with all logins; thus far it has only happened with the one account.

Can you point us towards this error is thrown?
