### ISSUE TITLE
Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by ZASMan** [synth/omniauth-microsoft_graph#6]
I'm currently following the [Ruby Connect Rest Sample](https://github.com/microsoftgraph/ruby-connect-rest-sample) and using this gem to authenticate. I've done the necessary setup, put in the environmental variables, but after it redirects to microsoft and and I give permission to my email to access the application, it never redirects to my app URL and throws this error:

<img width="1067" alt="screen shot 2018-05-02 at 1 30 08 pm" src="https://user-images.githubusercontent.com/13513340/39539809-bb55553a-4e0e-11e8-8bca-03242b632e85.png">

**Comment by Onumis** [comment]
Also got this. It happened during the connection to get the "raw_info": `access_token.get('https://graph.microsoft.com/v1.0/me')`

It started working after awhile... Since it took around 60s for this request to raise an error, I think it was something about Microsoft...

**Comment by synth** [comment]
Closing because of lack of response.
