### ISSUE TITLE
Release 0.1.1 on rubygems?

### ISSUE THREAD

**Issue by Onumis** [synth/omniauth-microsoft_graph#8]
You should release the latest version on to rubygems, or at least add this to the README:

```
gem 'omniauth-microsoft_graph', github: 'synth/omniauth-microsoft_graph',
                                                     ref: '5ac8cedcd660ac1ead'
```

Lost a good bunch of time trying to figure out why I was getting "deprecation" errors :(

**Comment by synth** [comment]
Sorry!
