### ISSUE TITLE
This gem clashes with msgraph-sdk-ruby

### ISSUE THREAD

**Issue by Onumis** [synth/omniauth-microsoft_graph#9]
Adding both gems to Gemfile:

```
gem 'omniauth-microsoft_graph'

gem 'microsoft_graph'
```

And then using a rails console:

```
> MicrosoftGraph
Traceback (most recent call last):
        1: from (irb):1
NameError (uninitialized constant MicrosoftGraph)
```

This happens (I think) because both gems have a `lib/microsoft_graph.rb` file, which causes `require 'microsoft_graph'` to fail.

You can get a similar result with IRB:

Requiring microsoft_graph first :heavy_check_mark: 
```
$ irb
2.5.1 :001 > require 'microsoft_graph'
 => true 
2.5.1 :002 > MicrosoftGraph
 => MicrosoftGraph 
2.5.1 :003 > require '/home/nuno/.rvm/gems/ruby-2.5.1/bundler/gems/omniauth-microsoft_graph-5ac8cedcd660/lib/microsoft_graph.rb'
 => true 
2.5.1 :004 > OmniAuth::Strategies::MicrosoftGraph
 => OmniAuth::Strategies::MicrosoftGraph
```

Requiring omniauth-microsoft_graph first :boom: 
```
$ irb
2.5.1 :001 > require '/home/nuno/.rvm/gems/ruby-2.5.1/bundler/gems/omniauth-microsoft_graph-5ac8cedcd660/lib/microsoft_graph.rb'
 => true 
2.5.1 :002 > OmniAuth::Strategies::MicrosoftGraph
 => OmniAuth::Strategies::MicrosoftGraph
2.5.1 :003 > require 'microsoft_graph'
 => true 
2.5.1 :004 > MicrosoftGraph
Traceback (most recent call last):
        2: from /home/nuno/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        1: from (irb):4
NameError (uninitialized constant MicrosoftGraph)
```

See:
https://github.com/microsoftgraph/msgraph-sdk-ruby/blob/master/lib/microsoft_graph.rb

Not sure how to solve this, but perhaps having a the prefix: `omniauth-` in that file would solve it?

**Comment by synth** [comment]
Thanks for this report. I don't have time to fix this, but happy to review a PR!

**Comment by afkplus** [comment]
Using @Onumis' suggestion I created this PR to resolve the conflict: https://github.com/synth/omniauth-microsoft_graph/pull/10.

**Comment by Onumis** [comment]
`option :name, :microsoft_graph` should also chance, or when using the gem devise, the auto loader for strategies will try to do a `require 'microsoft_graph'`. 

This is where I got stuck and ended up coping the strategy class into my lib and changing:
- the class name to `OmniAuth::Strategies::MicrosoftGraphOauth2`
- the `option :name, :microsoft_graph_oauth2` 
- and on for devise on a rails app:

```
# config/initializers/devise.rb
...
  require './lib/omniauth/strategies/microsoft_graph_oauth2.rb'
  config.omniauth :microsoft_graph_oauth2, ...

# app/models/user.rb
  devise ... :omniauthable, omniauth_providers: %i[
    developer
    google_oauth2
    microsoft_graph_oauth2
  ]
```
